### ISSUE TITLE
Broken for newer versions of Zig?

### ISSUE THREAD

**Issue by gmckeown** [tr1ckydev/zclock#3]
Trying to compile with Zig 0.15.2 and get this error:

error: root source file struct 'Io' has no member named 'getStdOut'

Possibly due to a change in 0.15.1: https://dev.to/bkataru/zig-0151-io-overhaul-understanding-the-new-readerwriter-interfaces-30oe

Reverting to Zig 0.14.1 via Homebrew allowed me to compile.
